package Server;

/**
 * This class provides an abstract exception that can be generated by
 * any magic server. This can be used to "wrap" other exceptions generated
 * by server implementations.
 * Created by Cameron Cagle on 11/5/2018.
 */
public class MagicServerException extends Exception {

    /**
     * Creates a new MagicServerException with no message.
     */
    public MagicServerException() {
        super();
    }

    /**
     * Creates a new MagicServerException with the specified message.
     * @param message -
     */
    public MagicServerException(String message){
        super(message);
    }

    /**
     * Creates a new MagicServerException with a specified message, and wraps
     * the specified throwable object.
     * @param message
     * @param throwable
     */
    public MagicServerException(String message, Throwable throwable) {
        super(message, throwable);
    }

    /**
     * Creates a new MagicServerException that wraps the specified Throwable object.
     * @param throwable - object to be wrapped.
     */
    public MagicServerException(Throwable throwable) {
        super(throwable);
    }
}
